.github/workflows/java.yml, .github/workflows/rust.yml, .github/workflows/swift.yml, java/Dockerfile, rust-toolchain
I picked 11/1 simply because that was what has been used for Java builds so far.
=> Pin nightly to a specific date

java/build.gradle
So I can get jimio to build a new release
=> Bump Java .jar to 0.1.3

.github/workflows/swift.yml, SignalClient.podspec, bin/build_helpers.sh
Also stop checking out libsignal-ffi.git for no reason.
=> Fix CocoaPod build to use rust-toolchain

.github/workflows/java.yml, .github/workflows/node.yml, .github/workflows/swift.yml
Swift doesn't care if JNI bridge changed, similarly for Java and the C ABI
=> Update GH actions to ignore changes to bridges

README.md
For those playing along at home
There isn't anything for Node in here, and I would guess the Swift instructions could be more complete, but it's a start. [@jrose-signal feel free to push instructions for Node and/or Swift as a commit on this branch]
=> Add some basic build instructions to the readme

java/java/build.gradle, java/tests/src/test/java/org/signal/libsignal/metadata/SealedSessionCipherTest.java, java/tests/src/test/java/org/signal/libsignal/metadata/TestInMemorySignalProtocolStore.java, java/tests/src/test/java/org/signal/libsignal/metadata/certificate/SenderCertificateTest.java, java/tests/src/test/java/org/signal/libsignal/metadata/certificate/ServerCertificateTest.java
Accidentally omitted from import in #21
=> Import the libsignal-metadata-java tests

SignalClient.podspec, node/build_node_bridge.sh, swift/build_ffi.sh
=> Fix quoting in Swift and Node build scripts

.github/workflows/shellcheck.yml, bin/build_helpers.sh, swift/build_ffi.sh
=> Enforce that our scripts are Shellcheck-clean

.flake8, .github/workflows/lints.yml, rust/bridge/jni/bin/gen_java_decl.py
We only have one for now, but we can start enforcing this now.
=> Add flake8 for checking our Python scripts

README.md
Otherwise you just have to scroll back up, but this is Markdown and we're all pro users here
=> Link to Swift in the README

java/java/build.gradle
I can't repro #99 locally, hoping this at least gives some hint
=> Have Maven log stack traces of tests that fail with exceptions

rust/protocol/src/proto/storage.proto
Suggested by @charlesmchen-signal.
=> Comment protobuf definitions where order matters for repeated fields

java/java/src/main/java/org/signal/internal/Native.java, java/java/src/main/java/org/whispersystems/libsignal/state/SessionRecord.java, java/java/src/main/java/org/whispersystems/libsignal/state/SessionState.java, rust/bridge/jni/src/lib.rs, rust/protocol/src/state/session.rs
Leaving only a few bits still directly used by Android
=> Remove more of SessionState from the Java binding

.github/workflows/build_and_test.yml
Hopefully avoiding bugs like #117
=> Cross build the Rust code for iOS

.github/workflows/build_and_test.yml, java/java/src/main/java/org/signal/internal/Native.java, rust/bridge/jni/bin/Native.java.in, rust/bridge/jni/bin/gen_java_decl.py
And bump the copyright years to 2021.
=> Add a --verify option to gen_java_decl.py

node/index.ts, node/libsignal_client.d.ts, node/test/PublicAPITest.ts, rust/bridge/node/src/lib.rs
~Mostly good to go except I need to work out the error handling strategy, right now there is a lot of `unwrap`~
=> Add PublicKey and PrivateKey for Node

java/tests/src/test/java/org/whispersystems/libsignal/SessionCipherTest.java, rust/protocol/src/session_cipher.rs
There were two discrepancies between the logic here and the original logic of libsignal-protocol-java.
First, if the session record had an uninitialized active session, in Java this would still attempt decryption with the old session states, but Rust would stop immediately without trying the old states. [I am not sure if this ever happens but it could possibly occur due to use of archiveCurrentState]
Secondly, we returned the wrong error condition. We treated lack of a sender chain as an invalid state (effectively an internal error) but Java treats it as an invalid message, which makes sense in so far as it is a message which we are unable to process with the information we have available. This wrong error type led to an unexpected exception being thrown in Android.
=> Fix handling when attempting to decrypt with a session that isn't found

java/build.gradle
This picks up #135 and #134 which were causing problems for Android.
=> Bump Java version to 0.2.1 for release

rust/bridge/shared/macros/src/lib.rs, rust/bridge/shared/src/jni/convert.rs
That distinction can be made in the main library by always doing a two-step "borrow-then-load", where sometimes the "borrow" operation is a no-op. This makes it easier to support inputs of the form `Option<&PublicKey>`, which shows up in the pre-key operations.
=> JNI: bridge_fn should not care about refs vs values at the macro level

java/build.gradle
Picking up the error handling changes.
=> Bump Java to 0.2.3

node/index.ts, node/test/PublicAPITest.ts
Aes256GcmSiv
ProtocolAddress
PreKeyRecord
PreKeyBundle
PreKeySignalMessage
SignalMessage
=> More Node bindings

rust/bridge/shared/src/node/convert.rs
There's a "dereference"-type operation that Neon should support for boxed Rust values but doesn't,
neon-bindings/neon#678. This commit adjusts the ArgTypeInfo implementation for mutable handles (#172) to account for that, so that if/when that operation gets added the only thing that will change is the unsafe code, not any of associated types.
=> Node: reduce compiler-unsafety by being more explicit about lifetimes

.github/workflows/build_and_test.yml, Cargo.lock, java/build.gradle, java/java/src/main/java/org/signal/internal/Native.java, rust/bridge/jni/Cargo.toml, rust/bridge/jni/bin/Native.java.in, rust/bridge/jni/bin/gen_java_decl.py, rust/bridge/jni/src/lib.rs, rust/bridge/jni/src/logging.rs, rust/protocol/Cargo.toml, rust/protocol/src/address.rs, rust/protocol/src/protocol.rs, rust/protocol/src/ratchet/keys.rs, rust/protocol/src/session.rs, rust/protocol/src/session_cipher.rs, rust/protocol/src/state/session.rs
Creating a 0.1.6 based on the 0.1.5 release since for whatever reason that has not been hitting the UndefinedLinkError issue on the Android 5 devices.
=> Backport logging changes onto 0.1.5 for Android

rust/protocol/src/sealed_sender.rs
See [SMKSenderCertificateTest.swift](https://github.com/signalapp/SignalMetadataKit/blob/7addcc1c4bb837b3ad44a05f72bf18ad8869b30c/SignalMetadataKitTests/src/SMKSenderCertificateTest.swift#L165).
=> Port over an iOS test for SenderCertificates with new fields

java/java/src/main/java/org/whispersystems/libsignal/SessionBuilder.java, java/java/src/main/java/org/whispersystems/libsignal/SessionCipher.java
=> Move the burden of SessionCipher locking to the client.

node/index.ts, node/libsignal_client.d.ts, node/test/PublicAPITest.ts, rust/bridge/node/bin/libsignal_client.d.ts.in, rust/bridge/node/src/lib.rs, rust/bridge/shared/src/lib.rs, rust/protocol/src/identity_key.rs, rust/protocol/src/sealed_sender.rs, swift/Sources/SignalFfi/signal_ffi.h
~Not complete -still missing~
And needs more TS tests.
=> TS store APIs

rust/bridge/shared/src/node/convert.rs
[A JsBuffer owns its storage](https://nodejs.org/api/n-api.html#n_api_napi_get_buffer_info), so it's safe to assume the buffer won't get deallocated. What's unsafe is assuming that no one else will modify the buffer while we have a reference to it, which is why we checksum it. (We can't stop the Rust compiler from potentially optimizing out that checksum, though.)
To keep from slowing down operations too much, the checksum is limited to the first 1024 bytes of a buffer unless debug logging is turned on.
=> Node: assume (but verify) that Buffers aren't modified while in use

.github/workflows/build_and_test.yml
`--all-targets` to include tests, `--workspace` to include non-default packages.
=> GitHub: Fix Clippy invocation for real

Cargo.lock, rust/bridge/shared/Cargo.toml, rust/bridge/shared/macros/Cargo.toml, rust/bridge/shared/macros/src/ffi.rs, rust/bridge/shared/macros/src/jni.rs, rust/bridge/shared/macros/src/lib.rs, rust/bridge/shared/macros/src/node.rs, rust/bridge/shared/src/jni/mod.rs
And clean up some other minor things while here. No intended functionality change.
=> Bridge: break up bridge_fn implementation by FFI/JNI/Node

node/index.ts, node/libsignal_client.d.ts, rust/bridge/shared/src/protocol.rs
=> Expose HasCurrentState for Node

node/test/PublicAPITest.ts, rust/bridge/shared/src/ffi/mod.rs, rust/bridge/shared/src/jni/mod.rs, rust/bridge/shared/src/node/convert.rs, rust/bridge/shared/src/node/mod.rs, rust/bridge/shared/src/node/storage.rs
=> Add a test of hasCurrentState

Cargo.lock, rust/bridge/node/Cargo.toml, rust/bridge/node/futures/Cargo.toml, rust/bridge/node/futures/tests-node-module/Cargo.toml, rust/bridge/shared/Cargo.toml, rust/bridge/shared/src/node/convert.rs
And remove the FinalizableOption workaround.
=> Node: update to Neon 0.8.0

.github/FUNDING.yml, README.md, SECURITY.md, SignalClient.podspec, swift/README.md, swift/build_ffi.sh
Improve our landing page and our GitHub metadata.
=> Update README, add FUNDING.yml, add SECURITY.md

rust/protocol/src/group_cipher.rs, rust/protocol/src/sender_keys.rs
...similar to what we have for 1:1 session encrypt/decrypt. There's a little less here because SenderKey sessions are one-sided and so they can't get out of sync the same way.
=> Add some logging for SenderKey operations

java/java/src/main/java/org/signal/internal/Native.java, java/java/src/main/java/org/signal/libsignal/metadata/SealedSessionCipher.java, java/tests/src/test/java/org/signal/libsignal/metadata/SealedSessionCipherTest.java, node/Native.d.ts, node/index.ts, node/test/PublicAPITest.ts, rust/bridge/jni/bin/gen_java_decl.py, rust/bridge/node/bin/gen_ts_decl.py, rust/bridge/shared/src/ffi/convert.rs, rust/bridge/shared/src/jni/convert.rs, rust/bridge/shared/src/jni/mod.rs, rust/bridge/shared/src/node/convert.rs, rust/bridge/shared/src/protocol.rs, rust/protocol/src/sealed_sender.rs, rust/protocol/tests/groups.rs, rust/protocol/tests/sealed_sender.rs, swift/Sources/SignalClient/SealedSender.swift, swift/Sources/SignalFfi/signal_ffi.h, swift/Tests/SignalClientTests/SessionTests.swift
Reverts signalapp/libsignal-client#302. Accidentally clicked merge on the wrong PR.
=> Revert "Add registration IDs to the Sealed Sender v2 upload (encrypt) format"

rust/protocol/src/sealed_sender.rs
This changes the encoding only; the change in API to provide real registration IDs will come in a follow-up.
=> Add registration IDs to the Sealed Sender v2 upload (encrypt) format

.github/workflows/build_and_test.yml, .github/workflows/npm.yml
=> GitHub: "Publish to NPM" action should always check out the same ref

Cargo.lock, Cargo.toml, SignalClient.podspec, java/build.gradle, package.json, rust/bridge/ffi/Cargo.toml, rust/bridge/jni/Cargo.toml, rust/bridge/node/Cargo.toml, rust/bridge/shared/Cargo.toml
Cherry-pick of #308, plus a version bump.
=> Cherry-pick our Neon fork to a new 0.5.2 build

rust/bridge/shared/src/jni/convert.rs
...because we support 32-bit platforms, and that's not correct.
=> JNI: don't reinterpret-cast a slice of longs as a slice of pointers

Cargo.lock, Cargo.toml
=> Update to (our fork of) Neon 0.8.3

binding.gyp, node/build_node_bridge.py
This fixes the build on openSUSE Tumbleweed.
=> node: Build node modules with python3

Cargo.lock, rust/hsm-enclave/Cargo.toml, rust/hsm-enclave/src/lib.rs
=> Add info log for connecting successfully to code.

.github/workflows/build_and_test.yml, bin/verify_duplicate_crates
Otherwise, we're not testing what we think we're testing.
=> GitHub: Make sure lockfiles don't get rewritten during testing

rust/protocol/fuzz/fuzz_targets/interaction.rs
Recommended to review with whitespace diffing turned off.
=> Clean up fuzz test, and correctly guard against over-archiving

node/Address.ts, node/NativeImpl.ts, node/index.ts
This logic is a bit finicky and it's better not to repeat it.
=> node: Factor out loading the native module into its own file
