signalapp/libsignal-client

java/java/src/main/java/org/whispersystems/libsignal/ecc/ECPublicKey.java, rust/bridge/jni/src/lib.rs
- Allow info to be null/empty in HKDF arguments. This is used during KBS attestation.
- Allow creating an ECPublicKey from the un-typed key bytes, also used when talking to KBS.
=> Fixes for Android

.github/workflows/rust.yml, Cargo.toml
Some of them have external requirements that may not be installed.
=> Rust: don't build any bridge/* crates by default

java/java/src/main/java/org/signal/internal/Native.java, rust/bridge/jni/bin/Native.java.in, rust/bridge/jni/bin/gen_java_decl.py, rust/bridge/jni/cbindgen.toml, rust/bridge/jni/src/lib.rs, rust/bridge/jni/src/util.rs
Working on the sealed sender code made me realize how obnoxious it is to keep Native.java vs JNI lib.rs in sync.
This is ugly, but it works.
The changes in bridge/jni just change ABI from "system" to "C" as cbindgen doesn't recognize "system" fns for whatever reason. The ABIs should be the same for our purposes.
=> Automatically generate Native.java from the exported symbols of the Rust bridge

.github/workflows/swift.yml, swift/Tests/SignalClientTests/PublicAPITests.swift
Can we configure the Swift linter to fail on all warnings?
=> Fix some Swift lint warnings

.github/workflows/java.yml, .github/workflows/node.yml, .github/workflows/swift.yml
I noticed in #55 when I added `--strict` to the options in `swift.yml` it triggered builds of Node and Java when it didn't need to.
I am not loving the combinatorial explosion going on here but don't know of a good way to get around at. At least we are fairly unlikely to add many more supported languages.
=> Have each language ignore changes to other workflow scripts

swift/build_ffi.sh
This wasn't caught by CI because it doesn't test any of the script options. My bad for not testing it myself.
=> Fix build script for macOS's old version of bash

rust/bridge/ffi/src/lib.rs, rust/bridge/ffi/src/util.rs, rust/bridge/jni/src/lib.rs, rust/bridge/jni/src/util.rs
The underlying APIs are async only because it supports async callbacks; if all the callbacks complete synchronously, the top-level API will too. We can avoid any sort of thread-local overhead by just expecting that (i.e. panicking if it's not true).
The duplication here is unfortunate but we're still hoping to merge these libraries.
=> Use a helper to expect our "async" calls to complete synchronously

bin/build_helpers.sh
Fixes #63 and its mystifying errors.
=> build_helpers.sh: fix error message if Rust isn't installed

rust/bridge/ffi/src/lib.rs, rust/bridge/ffi/src/util.rs, swift/Sources/SignalClient/state/SessionRecord.swift
This is necessary for the "reset session" user-level operation. I believe it's also our first mutating operation!
=> Swift: expose SessionRecord.archiveCurrentState()

bin/build_helpers.sh
This is the default per-user install location. Trying using the user's default shell isn't good enough without it being a login shell.
Should resolve the *actual* issue people were having in #63, rather than just the poor UX.
=> Change rustup fallback search to just look in ~/.cargo

java/Dockerfile, java/Makefile
- Remove unnecessary extra copy of rust-toolchain
- Skip Gradle's daemon when building in Docker
=> Docker: small improvements

java/build.gradle, java/tests/src/test/java/org/whispersystems/libsignal/SessionBuilderTest.java, java/tests/src/test/java/org/whispersystems/libsignal/TestNoSignedPreKeysStore.java, rust/bridge/jni/src/lib.rs, rust/bridge/jni/src/util.rs
One of the error states for `JNIEnv::call_method` is "threw an exception", so if we want to handle exceptions we have to do it before propagating the JNI error. On top of that, PreKeyStore and SignedPreKeyStore use exceptions to indicate the load of a pre-key that doesn't exist, so we need to handle that explicitly rather than treating it as a generic failure.
=> JNI: fix exception checks

bin/build_helpers.sh
Clarify the use of a specific Rust toolchain as discussed in #81.
=> Tweak error message to account for Rust without rustup

java/build_jni.sh
This means this is on for Android and iOS, but still off for Desktop, because we don't have a stripping story for Electron yet. (It doesn't matter for secrecy but it does affect download size at least a bit.)
=> Java: Generate debug symbols for the native Rust library

Cargo.lock, java/java/src/main/java/org/signal/internal/Native.java, java/java/src/main/java/org/signal/libsignal/crypto/Aes256GcmSiv.java, java/java/src/main/java/org/whispersystems/libsignal/util/Hex.java, java/tests/src/test/java/org/signal/libsignal/crypto/Aes256GcmSivTests.java, rust/aes-gcm-siv/Cargo.toml, rust/aes-gcm-siv/src/aes.rs, rust/aes-gcm-siv/src/aes/aarch64.rs, rust/aes-gcm-siv/src/aes_gcm_siv.rs, rust/aes-gcm-siv/src/cpuid.rs, rust/aes-gcm-siv/src/error.rs, rust/bridge/ffi/Cargo.toml, rust/bridge/ffi/cbindgen.toml, rust/bridge/ffi/src/lib.rs, rust/bridge/ffi/src/util.rs, rust/bridge/jni/Cargo.toml, rust/bridge/jni/bin/gen_java_decl.py, rust/bridge/jni/src/lib.rs, rust/bridge/jni/src/util.rs, swift/Sources/SignalClient/Aes256GcmSiv.swift, swift/Tests/SignalClientTests/PublicAPITests.swift
One thing I ran into, Android's `libc` crate doesn't support `getauxval`. Probably because it was not available in old API versions (added in 18) and Rust's support for weak symbols isn't great. So this PR disables detection of the ARMv8 instructions on Android. Hopefully I can just get `getauxval` added for Android (https://github.com/rust-lang/libc/issues/1987) otherwise I'll have to do something horrible like parsing `/proc/cpuinfo` :sob: I missed this problem in my testing as I built for Linux/aarch64 so I could test it under `qemu`.
I'll do TS in a followup PR on top of #95
=> Expose AES-GCM-SIV to Java and Swift

.github/workflows/build_and_test.yml, Cargo.lock, SignalClient.podspec, rust/bridge/ffi/Cargo.toml, rust/bridge/ffi/src/lib.rs, rust/bridge/ffi/src/logging.rs, swift/Package.swift, swift/PodLibLint.xcconfig, swift/README.md, swift/Sources/SignalClient/Logging.m, swift/Tests/SignalClientTests/PublicAPITests.swift, swift/Tests/SignalClientTests/SessionTests.swift, swift/Tests/SignalClientTests/TestCaseBase.swift
We're not actually logging anything yet, but this will let us do so. The logging is initialized using a static constructor so that clients of SignalCoreKit don't have to do any additional setup. This requires an ObjC file instead of a Swift one. (When running as a Swift package, logs will just go to stderr via NSLog.)
=> Swift: connect Rust's 'log' to SignalCoreKit's OWSLogger

.github/workflows/build_and_test.yml, Cargo.lock, node/build_node_bridge.sh, node/index.ts, node/libsignal_client.d.ts, package.json, rust/bridge/node/Cargo.toml, rust/bridge/node/src/lib.rs, yarn.lock
We lose the ability to define classes in Rust, but we probably want to be doing that in TypeScript anyway. A big advantage here is we're no longer dependent on the Node version.
=> Node: Switch to Neon's napi-runtime and JsBox

swift/Sources/SignalClient/DataStoreInMemory.swift, swift/Sources/SignalClient/DataStoreProtocols.swift, swift/Sources/SignalClient/Protocol.swift, swift/Sources/SignalClient/SealedSender.swift, swift/Sources/SignalClient/Utils.swift, swift/Sources/SignalClient/messages/SenderKeyDistributionMessage.swift, swift/Tests/SignalClientTests/PublicAPITests.swift, swift/Tests/SignalClientTests/SessionTests.swift
...instead of a bare UnsafeMutableRawPointer.
The "most correct" thing to do would be to have the context be an associated type of each store, and then clients would set them to the correct type, and they'd all have to be compatible when using multiple stores in an operation. However, this falls down in practice because Swift doesn't allow values to have protocol type for protocols with associated type, and the iOS framework SignalMetadataKit (and plenty of tests) do in fact want to reference the store types without having to use concrete types. Additionally, preserving that type through the C function shims used in each with*Store function would require a lot of extra work, since Swift generics are not monomorphized (resolved down to concrete types at compile time).
Instead, use a marker …
=> Swift: Use a marker protocol for store "context" parameters

bin/build_helpers.sh, java/android/build.gradle, java/build_jni.sh, node/build_node_bridge.sh
Thanks to @alan-signal for the first part, which allows running `gradlew android:connectedDebugAndroidTest` if you have an Android emulator running. I haven't added it to CI because (a) there doesn't seem to be a standard way to run an Android emulator on GitHub Actions*, and (b) Alan pointed out that as we get higher-level APIs, we'll probably start using Android OS features that will be mocked when run locally, and we wouldn't want to run a mocked system inside the emulator.
Still wanted: skip building the desktop library if you're building for Android. (You can skip Android via `env -u ANDROID_HOME`.)
\* I did look at [android-emulator](https://github.com/marketplace/actions/android-emulator) and [android-emulator-runner](https://github.com/marketplace/actions/android-emulator-runner) …
=> Get local and Android device tests working correctly

java/java/src/main/java/org/signal/internal/Native.java, java/java/src/main/java/org/whispersystems/libsignal/SessionCipher.java, java/java/src/main/java/org/whispersystems/libsignal/state/SessionRecord.java, java/java/src/main/java/org/whispersystems/libsignal/state/SessionState.java, java/tests/src/test/java/org/whispersystems/libsignal/SessionBuilderTest.java, java/tests/src/test/java/org/whispersystems/libsignal/SessionCipherTest.java, java/tests/src/test/java/org/whispersystems/libsignal/SimultaneousInitiateTests.java, java/tests/src/test/java/org/whispersystems/libsignal/ratchet/RatchetingSessionTest.java, rust/bridge/jni/src/lib.rs, rust/bridge/jni/src/util.rs, rust/protocol/src/state/session.rs
We have to leave the protobufs around, along with SessionState, as Android uses these directly for various purposes. I'm going to try to get some changes into Android to remove those as most uses are trivial and then we can remove some more of the Java API.
=> Cleanup Java Session logic

rust/bridge/ffi/src/lib.rs, rust/bridge/jni/src/lib.rs, rust/protocol/src/lib.rs, rust/protocol/src/ratchet.rs, rust/protocol/src/session_cipher.rs, rust/protocol/src/state/session.rs, rust/protocol/tests/ratchet.rs, rust/protocol/tests/session.rs, rust/protocol/tests/support/mod.rs
Remove some functions which were not used within the crate or the bindings.
Also fix some type errors in the JNI binding (introduced in #107) - SessionState was being used instead of SessionRecord, and this happened to work because the first element of a SessionRecord is an `Option<SessionState>`
End goal is removing `SessionState` from the crate exports entirely but we need to do a new release and update Android first.
=> Make most of Rust's SessionState pub(crate)

rust/protocol/src/ratchet/params.rs
Why was this re-exporting the type with a new name?
=> Clean up some imports

rust/protocol/src/lib.rs, rust/protocol/src/ratchet.rs, rust/protocol/src/session_cipher.rs
Hide some things that were exported to be used during intermediate steps of the JNI conversion (ChainKey, etc) and also some functions which were exposed but never needed by anything.
=> Hide more of the Rust API

java/build.gradle
Arbitrarily bumping the minor version to signify more notable changes than prior versions, eg
- Sealed sender now in Rust
- Removed protobufs from Java
- Partial removal of SessionState from Java
- Adding AES-GCM-SIV
=> Bump the Java version number

.github/workflows/build_and_test.yml, rust/aes-gcm-siv/src/lib.rs, rust/bridge/ffi/src/lib.rs, rust/bridge/jni/src/lib.rs, rust/bridge/shared/src/lib.rs, rust/protocol/src/lib.rs
Warnings don't need to be immediately fixed locally, and they make it harder to test with newer nightlies. CI is the place to enforce it.
=> Rust: Move deny-warnings behavior into CI

swift/Sources/SignalClient/state/SenderKeyRecord.swift
Fixes #120
I am not happy that this is not caught by the compiler. A grep seems to indicate this was the only such mistake.
Possibly ClonableOwnerHandle.handle should be `fileprivate`?
=> Use the correct handle

swift/build_ffi.sh
Rust build scripts and proc-macros are compiled for the host, rather than the target, which means they need a search path to link against the host's libraries. macOS Big Sur doesn't provide that in the default search paths anymore, so we add one manually based on an environment variable provided by Xcode.
Fixes #84.
=> Swift: fix Xcode build on Big Sur

rust/protocol/src/fingerprint.rs, rust/protocol/src/proto/fingerprint.proto
The encoding test was generated before switching to proto2 so we can feel comfortable that nothing is broken.
The encoding does change in the case of version == 0 since in proto2 the value is still included whereas in proto3 the version would be omitted in that case. This is harmless in this situation since the earliest valid fingerprint version is 1.
=> Convert fingerprints to use proto2 encoding

java/java/src/main/java/org/signal/internal/Native.java, java/java/src/main/java/org/whispersystems/libsignal/IdentityKey.java, java/java/src/main/java/org/whispersystems/libsignal/IdentityKeyPair.java, rust/bridge/jni/bin/gen_java_decl.py, rust/bridge/jni/src/lib.rs
This PR adds jni glue code for the `IdentityKeyPair` `deserialize` method and makes the `serialize` method public, as it was previously in the libsignal-protocol-java library.
The `IdentityKeyPair` consists of a private and public key, so the deserialize method needs to return a handle for each key. I've implemented the tuple as a simple java array with two elements. It's not very type safe but seemed the simplest solution here.
Is this something you'd consider merging?
I use these two methods in my signal-cli project.
=> Implement IdentityKeyPair Deserialize

java/tests/src/test/java/org/whispersystems/libsignal/SessionRecordTest.java, rust/bridge/jni/src/lib.rs, rust/protocol/src/state/session.rs, rust/protocol/tests/sealed_sender.rs
In libsignal-protocol-java, SessionRecord holds a SesssionState struct which is the "active" session plus a list of old states. If the record is freshly created, there is still a SessionState, but it is an uninitialized/new protobuf structure which causes all fields to be empty/zero/false.
So in the original Java logic you can call for example hasSenderChain, and on an empty/fresh record it will return false. However in Rust, in this case the Option is empty and we return an error instead.
For hasSenderChain, it seems reasonable to return false if there is no active session, since if there is no session there is certainly no chain.
Android also expects the session version to be == 0 on such sessions, but this makes less sense, so have this logic only in the Java binding and not in the …
=> Resolve difference in behavior between Java and Rust SessionRecord

.github/workflows/build_and_test.yml
2.0.0 is incompatible and behaves differently, would need work to adopt.
=> Pin cargo-ndk tool to 1.0.0

package.json
My hope is that `yarn pack` (on each build platform) will do the copying we need for the artifact repo, making it a drop-in change to use the source repo instead, but for now it's just there. `yarn build` addresses Jack's complaint in #124 that `yarn install` always calls `yarn node-gyp rebuild`, which does a clean.
=> Node: list files for `yarn pack`; add an alias `yarn build` for faster Rust turnaround

Cargo.lock, java/tests/src/test/java/org/whispersystems/libsignal/SessionBuilderTest.java, java/tests/src/test/java/org/whispersystems/libsignal/TestBadSignedPreKeysStore.java, rust/bridge/ffi/src/lib.rs, rust/bridge/ffi/src/util.rs, rust/bridge/jni/src/lib.rs, rust/bridge/jni/src/util.rs, rust/bridge/shared/Cargo.toml, rust/bridge/shared/src/ffi/error.rs, rust/bridge/shared/src/jni/error.rs, rust/bridge/shared/src/jni/mod.rs, rust/protocol/src/error.rs, rust/protocol/tests/groups.rs, rust/protocol/tests/sealed_sender.rs, rust/protocol/tests/session.rs, swift/.swiftlint.yml, swift/Sources/SignalClient/Utils.swift, swift/Tests/SignalClientTests/SessionTests.swift, swift/Tests/SignalClientTests/TestUtils.swift
Resolves #5, as well as providing the equivalent feature for Swift.
=> Propagate callback exceptions/errors when they fail the whole operation

binding.gyp, node/build_node_bridge.sh, node/index.ts
This will make it easier to have a combined artifact root for all supported platforms. Based on what RingRTC is doing, though without as much customization.
=> Node: name native library as libsignal_client_PLATFORM.node

Cargo.lock, java/java/src/main/java/org/signal/internal/Native.java, rust/bridge/ffi/Cargo.toml, rust/bridge/ffi/src/lib.rs, rust/bridge/ffi/src/util.rs, rust/bridge/jni/Cargo.toml, rust/bridge/jni/bin/gen_java_decl.py, rust/bridge/jni/src/lib.rs, rust/bridge/jni/src/util.rs, rust/bridge/shared/Cargo.toml, rust/bridge/shared/macros/Cargo.toml, rust/bridge/shared/macros/src/lib.rs, rust/bridge/shared/src/ffi/convert.rs, rust/bridge/shared/src/ffi/mod.rs, rust/bridge/shared/src/jni/convert.rs, rust/bridge/shared/src/jni/mod.rs, rust/bridge/shared/src/lib.rs, rust/bridge/shared/src/support.rs, swift/Sources/SignalClient/PublicKey.swift, swift/Sources/SignalClient/messages/PreKeySignalMessage.swift, swift/Sources/SignalFfi/signal_ffi.h
This is *one* approach to generic bridge functions that have the same body in FFI and JNI, with the only difference being input and output types. Here's what it looks like:
```rust
#[bridge_fn(ffi = "publickey_compare")]
fn ECPublicKey_Compare(key1: &PublicKey, key2: &PublicKey) -> i32 {
match key1.cmp(&key2) {
std::cmp::Ordering::Less => -1,
std::cmp::Ordering::Equal => 0,
std::cmp::Ordering::Greater => 1,
}
}
#[bridge_fn(ffi = "publickey_verify")]
fn ECPublicKey_Verify(
key: &PublicKey,
message: &[u8],
signature: &[u8],
) -> Result<bool, SignalProtocolError> {
key.verify_signature(&message, &signature)
}
```
This has a few moving pieces:
- `bridge_fn` is a proc-macro that expands into an FFI entry point and a JNI entry point, each of which call the original function. It classifies …
=> Support generic bridge functions for FFI/JNI

.github/workflows/build_and_test.yml, rust/protocol/benches/session.rs
I considered adding `cargo bench --no-run` to the GH actions build but that would add a whole second (release-mode) build to CI which I'm not sure is worth it.
=> Fix the session encrypt/decrypt benchmark code

rust/bridge/ffi/src/util.rs, rust/bridge/shared/src/jni/mod.rs, rust/protocol/Cargo.toml, rust/protocol/src/error.rs, rust/protocol/src/session_cipher.rs, rust/protocol/src/state/session.rs
Error log looks like this
```
Message from +14151111111:1 failed to decrypt; sender ratchet public key 01d5bbc17518fc09e3aa0cc7f43b627d5bce860f7bb2b1adc4676300569cbd30 message counter 1
Candidate session 0 failed with 'invalid ciphertext message', had 1 receiver chains
Receiver chain with sender ratchet public key 0501d5bbc17518fc09e3aa0cc7f43b627d5bce860f7bb2b1adc4676300569cbd30
Candidate session 1 failed with 'invalid ciphertext message', had 4 receiver chains
Receiver chain with sender ratchet public key 057b8c777abe702f861d6e77bf9d3b0a93a361ac24a2aa07cdbf52e413a4e61576
Receiver chain with sender ratchet public key 0571eab62e9ca2827962b7a41593bd76d2a7976762844af15d6ac1529af456ac0c
Receiver chain with sender ratchet public key 052dca6940acfb4a02da93bd649d400cfedf16156cff65fe0d6f4105b4295 …
```
=> Log more information when decryption fails

Cargo.lock, java/java/src/main/java/org/signal/internal/Native.java, rust/bridge/ffi/src/lib.rs, rust/bridge/ffi/src/util.rs, rust/bridge/jni/src/lib.rs, rust/bridge/jni/src/util.rs, rust/bridge/shared/Cargo.toml, rust/bridge/shared/macros/src/lib.rs, rust/bridge/shared/src/ffi/convert.rs, rust/bridge/shared/src/ffi/mod.rs, rust/bridge/shared/src/jni/convert.rs, rust/bridge/shared/src/jni/mod.rs, rust/bridge/shared/src/lib.rs, rust/bridge/shared/src/support.rs, swift/Sources/SignalClient/Aes256GcmSiv.swift, swift/Sources/SignalFfi/signal_ffi.h
I suggest reviewing commit-by-commit. In particular the commit that adds `bridge_fn_buffer` has much more going on than the others. It's a little unfortunate that that doesn't fall nicely out of the rest of the `bridge_fn` infrastructure, but the double output parameters for C and avoiding an extra copy for Java make it worth it in the end. Still, you can see it starting to pay off with the diff size.
=> Migrate a big chunk of FFI/JNI to bridge_fn

Cargo.lock, rust/bridge/node/Cargo.toml
Neon by default requires N-API 6 and the version of Electron that is used in Desktop only supports N-API 5. Without this feature, some weird hacks are required to build on Windows.
=> Bump Neon to 0.7.0 and use feature napi-1

rust/bridge/ffi/src/lib.rs, rust/protocol/src/state/session.rs, swift/Sources/SignalClient/state/SessionRecord.swift, swift/Sources/SignalFfi/signal_ffi.h, swift/Tests/SignalClientTests/SessionTests.swift
If a session has just been reset (`archiveCurrentState()`), then there won't be an active state in the session and sends will fail until a new session is properly established by the client.
=> Swift: add SessionRecord.hasCurrentState

Cargo.lock, node/build_node_bridge.sh, rust/bridge/node/Cargo.toml, rust/bridge/node/src/lib.rs, rust/bridge/shared/Cargo.toml, rust/bridge/shared/macros/src/lib.rs, rust/bridge/shared/src/ffi/convert.rs, rust/bridge/shared/src/jni/convert.rs, rust/bridge/shared/src/lib.rs, rust/bridge/shared/src/node/convert.rs, rust/bridge/shared/src/node/mod.rs, rust/bridge/shared/src/support.rs
This should in theory give us *all* of the functions already in libsignal-bridge for free. There are a few complicated bits:
- Borrowing a JsBuffer requires the JS engine to be locked, but returning a new buffer requires using the JS engine. That means having to incur a copy-in (for `&[u8]` parameters) or a copy-out (for `&[u8]` results) unless we make `bridge_fn` signatures more complicated. For now I've gone with a copy-in because it was easier to implement, but a copy-out probably makes more sense in the long run.
- I wanted to avoid Neon's explicit registration list because it was one more thing to keep in sync, so I've used the [`linkme`](https://docs.rs/linkme/0.2.4/linkme/index.html) crate to have the linker build a static list that can be iterated through at runtime. If you think …
=> Add support for Node to libsignal-bridge

Cargo.lock, node/index.ts, node/libsignal_client.d.ts, node/test/PublicAPITest.ts, rust/bridge/node/Cargo.toml, rust/bridge/node/src/lib.rs, rust/bridge/node/src/logging.rs, rust/bridge/shared/src/node/convert.rs, rust/bridge/shared/src/node/mod.rs
Sketch out a logging callback for Node clients, like #150 for Java and #90 for Swift.
=> Node: Add an entry point for logging

rust/bridge/node/src/logging.rs, rust/bridge/shared/macros/src/lib.rs, rust/bridge/shared/src/node/convert.rs, rust/bridge/shared/src/node/mod.rs
Follow-up from the similar change for JNI, #157. This should hopefully be simpler going forward.
=> Node: bridge_fn shouldn't care about refs vs values at the macro level

swift/Tests/SignalClientTests/TestCaseBase.swift
Unfortunately not implemented on Linux, instead one must convert to a C string and use %s
=> Avoid using %@ with NSLog

rust/protocol/src/sealed_sender.rs, rust/protocol/tests/sealed_sender.rs
Reserve one ID for testing
ServerCertificates are created by
https://github.com/signalapp/Signal-Server-Private/blob/master/service/src/main/java/org/whispersystems/textsecuregcm/workers/CertificateCommand.java I'm going to open a PR reserving this value there so we never have a tragic collision between test and prod values
=> Add the logic for handling revoked server certificates

rust/protocol/tests/sealed_sender.rs
Introduced by merging #118 
Don't really understand what happened here since this compiled fine with the same rustc when the PR was opened.
=> Fix compilation problem

package.json
This only made sense for using libsignal-client *directly* as a dependency; when used through a prebuilt "artifact repo" (see node/scripts/copy_repo.sh), there's no TypeScript to compile.
=> Node: remove "prepare" script

.github/workflows/build_and_test.yml, SignalClient.podspec, swift/Package.swift, swift/Sources/SignalClient/Address.swift, swift/Sources/SignalClient/Aes256GcmSiv.swift, swift/Sources/SignalClient/DataStoreProtocols.swift, swift/Sources/SignalClient/Error.swift, swift/Sources/SignalClient/Fingerprint.swift, swift/Sources/SignalClient/IdentityKey.swift, swift/Sources/SignalClient/Kdf.swift, swift/Sources/SignalClient/Logging.m, swift/Sources/SignalClient/PrivateKey.swift, swift/Sources/SignalClient/Protocol.swift, swift/Sources/SignalClient/PublicKey.swift, swift/Sources/SignalClient/SealedSender.swift, swift/Sources/SignalClient/SenderKeyName.swift, swift/Sources/SignalClient/Utils.swift, swift/Sources/SignalClient/messages/CiphertextMessage.swift, swift/Sources/SignalClient/messages/PreKeySignalMessage.swift, swift/Sources/SignalClient/messages/SenderKeyDistributionMessage.swift, swift/Sources/SignalClient/messages/SenderKeyMessage.swift, swift/Sources/SignalClient/messages/SignalMessage.swift, swift/Sources/SignalClient/state/PreKeyBundle.swift, swift/Sources/SignalClient/state/PreKeyRecord.swift, swift/Sources/SignalClient/state/SenderKeyRecord.swift, swift/Sources/SignalClient/state/SessionRecord.swift, swift/Sources/SignalClient/state/SignedPreKeyRecord.swift, swift/Sources/SignalFfi/module.modulemap, swift/Tests/SignalClientTests/TestCaseBase.swift
Three changes that allow libsignal-client to be prebuilt for iOS clients using [cocoapods-binary](https://github.com/leavez/cocoapods-binary):
- Use CocoaLumberjack directly instead of SignalCoreKit's OWSLog
- Move signal_ffi.h into SignalClient.framework (and add a hacky unstable compiler flag to keep the SwiftPM build working)
- Skip build_ffi.sh when the pod is prebuilt
=> Compatibility with cocoapods-binary

java/java/src/main/java/org/signal/internal/Native.java, node/libsignal_client.d.ts, rust/bridge/ffi/src/lib.rs, rust/bridge/ffi/src/util.rs, rust/bridge/jni/src/lib.rs, rust/bridge/node/bin/gen_ts_decl.py, rust/bridge/shared/macros/src/lib.rs, rust/bridge/shared/src/ffi/convert.rs, rust/bridge/shared/src/ffi/mod.rs, rust/bridge/shared/src/jni/convert.rs, rust/bridge/shared/src/lib.rs, rust/bridge/shared/src/node/convert.rs, rust/bridge/shared/src/node/mod.rs, rust/bridge/shared/src/support/mod.rs, swift/Sources/SignalFfi/signal_ffi.h
Neon enforces boxed values to be immutable, so I had to jump through some hoops with RefCell. FFI also expects an out-pointer for any declared results, but error-only results shouldn't get one. The easiest way to detect that was to add another macro variant, `bridge_fn_void`.
=> Support &mut arguments and Result<(), Error> results

Cargo.lock, rust/bridge/ffi/Cargo.toml, rust/bridge/ffi/cbindgen.toml, rust/bridge/ffi/src/lib.rs, rust/bridge/ffi/src/util.rs, rust/bridge/jni/Cargo.toml, rust/bridge/jni/src/lib.rs, rust/bridge/jni/src/util.rs, rust/bridge/node/Cargo.toml, rust/bridge/shared/Cargo.toml, rust/bridge/shared/src/ffi/convert.rs, rust/bridge/shared/src/ffi/error.rs, rust/bridge/shared/src/ffi/mod.rs, rust/bridge/shared/src/jni/convert.rs, rust/bridge/shared/src/jni/error.rs, rust/bridge/shared/src/jni/mod.rs, rust/bridge/shared/src/lib.rs, rust/bridge/shared/src/node/convert.rs, rust/bridge/shared/src/node/mod.rs, rust/bridge/shared/src/support/transform_helper.rs, rust/protocol/Cargo.toml, rust/protocol/benches/ratchet.rs, rust/protocol/benches/session.rs, rust/protocol/tests/groups.rs, rust/protocol/tests/ratchet.rs, rust/protocol/tests/sealed_sender.rs, rust/protocol/tests/session.rs, rust/protocol/tests/support/mod.rs
The project corresponds to libsignal-protocol-java and the others, but *within* the language we don't need to tag with the language name.
=> Drop the "-rust" from the "libsignal-protocol" crate

java/java/src/main/java/org/signal/internal/Native.java, java/java/src/main/java/org/whispersystems/libsignal/fingerprint/DisplayableFingerprint.java, node/libsignal_client.d.ts, rust/bridge/shared/src/lib.rs, swift/Sources/SignalFfi/signal_ffi.h
Was exposed in Java but never called by Android. Was included in the C ABI but no Swift binding.
Doesn't make any sense to use this because it just string formats the binary fingerprint but to generate that you need the fingerprint generator. We instead always use the formatted string from `NumericFingerprintGenerator_GetDisplayString`.
=> Remove DisplayableFingerprint_Format from bridge

swift/Sources/SignalClient/IdentityKey.swift, swift/Tests/SignalClientTests/PublicAPITests.swift
It called the underlying Rust entrypoint with the arguments in the wrong order. Fixes #155.
=> Swift: fix IdentityKeyPair.init(bytes:)

.github/workflows/build_and_test.yml, Cargo.lock, rust/bridge/ffi/Cargo.toml, rust/bridge/jni/Cargo.toml, rust/bridge/node/Cargo.toml, rust/bridge/shared/Cargo.toml
Updated the following crates to resolve duplication of cfg-if, which is a macro-only crate anyway.
- backtrace
- getrandom
- log (relaxed the version on it as well)
- polyval (still not at latest because it uses a newer cpuid-bool than sha2 does)
- sha2
=> Fix our duplicate crate checking, then resolve duplicate crates

rust/protocol/src/state/session.rs
Was browsing this client library for self-edification purposes. Saw what appeared to be a small inconsistency in your type aliases. 
No worries if Signal is not accepting pull requests for whatever reason.
=> type alias quickfix

.github/workflows/build_and_test.yml, Cargo.lock, bin/verify_crate_versions.py, rust/bridge/ffi/Cargo.toml, rust/bridge/ffi/src/logging.rs, rust/bridge/jni/Cargo.toml, rust/bridge/jni/src/logging.rs, rust/bridge/node/Cargo.toml, rust/bridge/node/src/logging.rs
Re the discussion on Android/libsignal-client group where the version of the lib being used wasn't clear to the Android team. Just log the version, then there is no ambiguity.
This requires we keep the crate version in sync with the release version but that doesn't seem terribly onerous.
Considered also logging the git hash and commit date using https://docs.rs/vergen/3.2.0/vergen/index.html but probably just a version is sufficient.
=> Log the SignalClient version when the logger is initialized

.github/workflows/build_and_test.yml, binding.gyp, node/build_node_bridge.py, node/index.ts
Needed for Apple Silicon/Windows arm64/Windows ia32
Ref https://github.com/signalapp/Signal-Desktop/issues/3745#issuecomment-777837619
Ref https://github.com/signalapp/Signal-Desktop/issues/1636#issuecomment-778153694
Ref https://github.com/signalapp/Signal-Desktop/issues/4461
**How to test**:
`npm_config_arch` is only needed when you're cross-compiling from a x64 host, e.g. x64 to ia32.
Branch with generated binaries: https://github.com/dennisameling/libsignal-client-node/tree/cross-compilation-compat/build
```
export npm_config_arch=ia32
yarn install
yarn tsc
```
Tested on:
=> Add node multi-arch/cross-compilation support

node/build_node_bridge.py
On Windows, the C runtime doesn't come preinstalled, so we need to link it to avoid passing a dependency on to our users.
=> Node: statically link the C runtime on Windows

package.json, yarn.lock
Also update indirect dependency `ini` (to v1.3.8), because v1.3.6 fixes a low-severity security issue. We're not using ini files at all in this package (`ini` is a devDependency via Electron), but it's still best not to have this around.
=> Node: Update to Electron 11.2.3 to match Desktop

java/java/src/main/java/org/whispersystems/libsignal/SessionBuilder.java, java/java/src/main/java/org/whispersystems/libsignal/SessionCipher.java
The lock inside of `SessionCipher` is causing a lot of pain due to the threading model of the Android app. Let's just move the entire responsibility of locking to the client.
=> Move the burden of SessionCipher locking to the client.

rust/bridge/ffi/src/util.rs, rust/bridge/shared/src/jni/mod.rs, rust/protocol/src/error.rs, rust/protocol/src/session_cipher.rs
Instead use the log integration
(We just had no log integration at the point that the decryption failure logging was needed)
=> Don't stuff long logs into error/exception messages

rust/bridge/jni/src/lib.rs, rust/bridge/jni/src/util.rs
The lifetime means the compiler can guarantee the object hasn't been garbage-collected.
=> JNI: Use JObject<'a> instead of jobject when possible

rust/bridge/node/src/lib.rs, rust/protocol/src/curve.rs, rust/protocol/src/fingerprint.rs, rust/protocol/src/group_cipher.rs, rust/protocol/src/identity_key.rs, rust/protocol/src/kdf.rs, rust/protocol/src/lib.rs, rust/protocol/src/protocol.rs, rust/protocol/src/ratchet.rs, rust/protocol/src/ratchet/keys.rs, rust/protocol/src/sealed_sender.rs, rust/protocol/src/sender_keys.rs, rust/protocol/src/session.rs, rust/protocol/src/session_cipher.rs, rust/protocol/src/state/bundle.rs, rust/protocol/src/state/prekey.rs, rust/protocol/src/state/session.rs, rust/protocol/src/state/signed_prekey.rs, rust/protocol/src/storage/inmem.rs, rust/protocol/src/storage/traits.rs
Remove free-standing functions in curve for signatures, etc - always call the version on the struct
Don't import anything via `curve::` anymore - always get these via `crate::`
Add impl of `TryFrom` where appropriate
Second commit is kind of unrelated (though inspired by the changes removing use of ``curve::`` in prior commit), but cleans up imports within `protocol` - if something is in the public API import it via ``crate::X`` rather than ``crate::random_submodule::X``.
=> Curve related cleanups

rust/protocol/tests/sealed_sender.rs
It would occasionally fail with an unexpected error, as in
https://github.com/signalapp/libsignal-client/runs/1938610036
=> Fix a flaky test

.github/workflows/build_and_test.yml, Cargo.lock, rust/aes-gcm-siv/tests/aes_gcm_siv.rs, rust/poksho/src/sign.rs, rust/poksho/src/statement.rs, rust/protocol/src/crypto.rs, rust/protocol/tests/sealed_sender.rs, rust/protocol/tests/session.rs, rust/protocol/tests/support/mod.rs
And tweak the GitHub Clippy enforcement so this doesn't regress.
I do feel better about marking Clippy lints as allowed *in tests* because sometimes the test is trying to test something that you wouldn't write in normal code, or can safely ignore something you wouldn't want to ignore in normal code. I do think it still makes sense to decide that on a test-by-test basis, though.
=> Fix or mark-as-allowed Clippy lints in tests

.github/workflows/build_and_test.yml, SignalClient.podspec, swift/Package.swift, swift/Sources/SignalClient/Address.swift, swift/Sources/SignalClient/Aes256GcmSiv.swift, swift/Sources/SignalClient/DataStoreProtocols.swift, swift/Sources/SignalClient/Error.swift, swift/Sources/SignalClient/Fingerprint.swift, swift/Sources/SignalClient/IdentityKey.swift, swift/Sources/SignalClient/Kdf.swift, swift/Sources/SignalClient/Logging.m, swift/Sources/SignalClient/PrivateKey.swift, swift/Sources/SignalClient/Protocol.swift, swift/Sources/SignalClient/PublicKey.swift, swift/Sources/SignalClient/SealedSender.swift, swift/Sources/SignalClient/SenderKeyName.swift, swift/Sources/SignalClient/Utils.swift, swift/Sources/SignalClient/messages/CiphertextMessage.swift, swift/Sources/SignalClient/messages/PreKeySignalMessage.swift, swift/Sources/SignalClient/messages/SenderKeyDistributionMessage.swift, swift/Sources/SignalClient/messages/SenderKeyMessage.swift, swift/Sources/SignalClient/messages/SignalMessage.swift, swift/Sources/SignalClient/state/PreKeyBundle.swift, swift/Sources/SignalClient/state/PreKeyRecord.swift, swift/Sources/SignalClient/state/SenderKeyRecord.swift, swift/Sources/SignalClient/state/SessionRecord.swift, swift/Sources/SignalClient/state/SignedPreKeyRecord.swift, swift/Sources/SignalFfi/module.modulemap, swift/Tests/SignalClientTests/TestCaseBase.swift, swift/build_ffi.sh
Reverts #163 in favor of an alternate approach to using cocoapods-binary that allows the Swift code to be built on the app side, avoiding some LLDB/Swift integration issues.
=> CocoaPods: Build the Rust library as part of installing the CocoaPod

Cargo.lock, SignalClient.podspec, rust/bridge/ffi/Cargo.toml
This skips the v0.2 series to bring it in line with the Java bridge.
=> CocoaPod: tag v0.3.0

Cargo.lock, Cargo.toml, rust/poksho/Cargo.toml, rust/protocol/Cargo.toml
As reusing the old branch breaks building zkgroup
=> Use a new branch for the 3.0.0 fork of curve25519-dalek

node/test/PublicAPITest.ts, rust/protocol/src/curve.rs
We clamp on generate but some clients will generate non-clamped keys expecting the operation will clamp, and as of now clients who deserialize such keys will produce incorrect results.
=> Always clamp private keys on deserialize

node/index.ts, node/libsignal_client.d.ts, node/test/PublicAPITest.ts, rust/bridge/shared/src/protocol.rs
As untyped errors make it difficult to detect this case vs other error conditions
=> Have TS binding return null on a sealed sender self-send

java/build.gradle, rust/bridge/jni/Cargo.toml
@jrose-signal Bumping from 0.2.3->0.4.0 to indicate new support for DeviceTransferKey, with the idea that next Swift build also goes to 0.4.0 (from current 0.3.1) for same reason. Seems ok?
=> Bump Java version to 0.3.4

.github/workflows/build_and_test.yml, Cargo.lock, Cargo.toml, rust/bridge/shared/macros/src/lib.rs, rust/protocol/tests/groups.rs, rust/protocol/tests/session.rs
We'll still run them in CI, but we don't need to run them locally.
=> By default, skip Rust tests that take over 10s in debug builds

bin/crates_code_size.bloaty
Only works on ELF, unfortunately. See https://github.com/google/bloaty.
=> Add a bloaty source that estimates code size contributions of crates

node/Native.d.ts, rust/bridge/shared/src/ffi/convert.rs, rust/bridge/shared/src/jni/convert.rs, rust/bridge/shared/src/node/convert.rs
It only matched exactly `$typ as false` so for example `$typ as false, mut = true` would cause the type to still be emitted.
There is probably a better way to resolve this, but this hack fixes my immediate issue
=> Fix bridge_handle! logic for disabling for certain targets

java/java/src/main/java/org/signal/internal/Native.java, java/java/src/main/java/org/signal/libsignal/crypto/Aes256Ctr32.java, java/java/src/main/java/org/signal/libsignal/crypto/Aes256GcmDecryption.java, java/java/src/main/java/org/signal/libsignal/crypto/Aes256GcmEncryption.java, java/tests/src/test/java/org/signal/libsignal/crypto/Aes256GcmEncryptionTests.java, rust/bridge/shared/src/crypto.rs, swift/Sources/SignalFfi/signal_ffi.h
As Java has no concept of slices and we need some way of doing partial updates, since this is required to implement the JCE Cipher interface, and Android uses it.
=> Support offset/length params for GCM encryption in Java API

java/java/src/main/java/org/signal/libsignal/crypto/Aes256Ctr32.java, java/java/src/main/java/org/signal/libsignal/crypto/Aes256GcmDecryption.java, java/java/src/main/java/org/signal/libsignal/crypto/Aes256GcmEncryption.java, java/java/src/main/java/org/signal/libsignal/crypto/jce/Cipher.java, java/java/src/main/java/org/signal/libsignal/crypto/jce/Mac.java, java/java/src/main/java/org/signal/libsignal/crypto/jce/MessageDigest.java
This is ugly and pretty limited but it should handle most of the cases Android uses `Cipher` with GCM. It might ease the transition to using the Rust-based GCM impl. IMO it's probably better in the long run to just change Android to use our directly provided APIs.
Hash and MAC should work just like JCE's, `Cipher` comes with a lot of caveats though. (Documented in the comments in `Cipher.java`)
=> Add a JCE compat layer

java/java/src/main/java/org/whispersystems/libsignal/groups/GroupCipher.java, java/java/src/main/java/org/whispersystems/libsignal/groups/GroupSessionBuilder.java
Same as #202 but for SenderKey encryption.
=> Java: Move burden of GroupCipher/SessionBuilder locking to the client

rust/bridge/node/futures/src/future.rs, rust/bridge/node/futures/src/future/builder.rs, rust/bridge/node/futures/src/lib.rs, rust/bridge/shared/macros/src/ffi.rs, rust/bridge/shared/macros/src/jni.rs, rust/bridge/shared/macros/src/lib.rs, rust/bridge/shared/macros/src/node.rs
In the hopes that they'll be more reusable that way. The remaining feature flags, `wake_trait` and `min_const_generics`, were both stabilized recently, so when we roll our compiler version forward we'll be able to eliminate them too.
Note that this is *not* going to get this repository off of nightly: the `crypto` crate still uses the `stdsimd` and `aarch64_target_feature` features on Android and iOS for access to intrinsics, and cbindgen always needs *some* nightly installed in order to support macros. But signal-neon-futures and libsignal-bridge-macros are potentially reusable elsewhere.
=> Start removing nightly features from support libraries

swift/Sources/SignalClient/Logging.m
commit 51a3b61ebae7a97f71a812b1b9909992e8013f9d (HEAD -> mlin/PR/LoggingLeak, public/mlin/PR/LoggingLeak, origin/mlin/PR/LoggingLeak)
Author: Michelle Linington <michelle@signal.org>
Date:   Fri Mar 26 20:38:43 2021 -0700
Core-52: libsignalclient leaks memory when setting up logging
initLogging() has __attribute__((constructor)), so it'll run before main
and before we have an autoreleasepool for the thread.
After logging is configured, it posts a log message which results in
some objects being autoreleased. This change adds a pool to track these
objects.
=> Core-52: libsignalclient leaks memory when setting up logging

node/test/PublicAPITest.ts, rust/protocol/src/protocol.rs
This slipped in the original translation to Rust, but it hasn't mattered in practice because both nibbles of the version byte have had the same value for a long time.
=> protocol: Test version bytes the same way as libsignal-protocol-java

node/Errors.ts, node/Native.d.ts, node/index.ts, node/test/PublicAPITest.ts, rust/bridge/node/bin/Native.d.ts.in, rust/bridge/shared/macros/src/node.rs, rust/bridge/shared/src/node/convert.rs, rust/bridge/shared/src/node/error.rs, rust/bridge/shared/src/node/mod.rs, rust/bridge/shared/src/protocol.rs
- After loading the Rust library into Node, set an 'Errors' property with the relevant error types on the module object.
- Whenever a `bridge_fn` produces an error, pass it to a new `SignalNodeError::throw` API along with the `this` object, which is assumed to have to be the object with the 'Errors' property.
This is a little less tidy than how we do Java exceptions, but it comes from not having access to the error classes by some kind of absolute name. Alternate approaches considered include:
- Use an initialized-once global. Downside: would not work if you ever had more than one Node engine live in a process, or quit and restarted it. Upside: available everywhere.
- Store the errors on the global object under some long, complicated key (like "org.signal.libsignal-client.Errors"). …
=> Bridge: add support for strongly-typed Node errors

SignalClient.podspec
Also, if the library somehow isn't built when used as a non-local CocoaPods dependency, don't suggest running swift/build_ffi.sh; CocoaPods will have removed it already. Re-running `pod install` is more likely to help, though in practice something's probably gone wrong in the configuration.
=> [CocoaPod] Properly quote path to libsignal_ffi.a in build script

rust/bridge/node/futures/Cargo.toml, rust/bridge/node/futures/benches/node.rs, rust/bridge/node/futures/tests-node-module/src/lib.rs, rust/bridge/node/futures/tests/node-tests/bench.js, rust/bridge/node/futures/tests/node-tests/package.json, rust/bridge/node/futures/tests/node-tests/test/basic.js, rust/bridge/node/futures/tests/node-tests/yarn.lock, rust/bridge/node/futures/tests/util.rs
It turns out this takes less than a millisecond, at least when the event loop is empty, but the setup might still be useful in the future. Run with `cargo bench -p signal-neon-futures`.
=> signal-neon-futures: Add a Node benchmark for a single round trip

rust/bridge/jni/build.rs
For some reason, the Docker build of libsignal_jni.so doesn't link to libdl, even though the build on my local machine does. This doesn't seem to be a problem on most phones, presumably because the libdl functions are re-exported through libc. However, on a small subset of Android phones this is not good enough and libsignal_jni.so fails to load. For now, work around this by forcing the Android cross-compilation linker to link to libdl (instead of doing it "as needed").
[Docs for `cargo:rustc-cdylib-link-arg`](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-cdylib-link-arg)
=> Android: force-link libdl

java/Dockerfile, java/docker/apt.conf, java/docker/dependencies.txt, java/docker/print-versions.sh, java/docker/sources.list
Debian has a more stable retention period for pinned dependencies (the version of OpenJDK 8 we were using for Ubuntu is gone already!), and it matches what the Signal-Android repository is doing.
=> Java: switch to Debian for Docker builds instead of Ubuntu

rust/protocol/src/error.rs
When using wrapper types like [`anyhow::Error`](https://docs.rs/anyhow/1.0.25/anyhow/struct.Error.html), it is required that all underlying error types are `Send`, `Sync`, and `'static`. I tried to compile the other crates (with all features) after this change, and it looks like it doesn't break anything.
=> Make sure SignalProtocolError is Sync

rust/protocol/src/session_cipher.rs, swift/Tests/SignalClientTests/SessionTests.swift
This joins the logging for when the session cipher fails; when pre-key processing fails (especially with a "no such pre-key" error), we want to see what state the session's in.
=> Log session state when we fail to process a pre-key

Cargo.lock, rust/crypto/Cargo.toml
See https://github.com/rust-lang/libc/commit/2eaa621a00a992bfda290457329a49c9a2847711, included in 0.2.93.
=> rust/crypto: bump libc to support getauxval on musl

rust/bridge/node/futures/src/executor.rs, rust/bridge/node/futures/src/lib.rs, rust/bridge/node/futures/src/promise.rs, rust/bridge/node/futures/tests-node-module/src/lib.rs
Node can more efficiently handle multiple tasks coming in on the same queue*, so remove the "convenience" APIs that derive a new queue from a Context, and require an existing EventQueue instead. This cuts more time off of our decryption benchmark (not checked in).
Additionally, run the first poll for the future synchronously, to avoid having to wait for the event loop to pick up the task to start the future.
\* or will be able to when nodejs/node#38506 is released
=> signal-neon-futures: Only run Rust futures on an existing EventQueue

node/Errors.ts, node/test/PublicAPITest.ts, rust/bridge/shared/src/node/error.rs
This was MessageCounterError in libtextsecure; it's an "error" in that it interrupts processing of an individual message, but that message is then discarded in practice.
=> Node: Make a dedicated error code for DuplicatedMessage

rust/bridge/node/futures/tests/node-tests/package.json, rust/bridge/node/futures/tests/node-tests/yarn.lock
This came from the Node template generated by a past version of Neon, but we don't need it and it brings in a bunch of extra dependencies.
=> signal-neon-futures: Remove neon-cli dependency from test module

java/java/src/main/java/org/signal/internal/Native.java, java/java/src/main/java/org/whispersystems/libsignal/protocol/PreKeySignalMessage.java, java/java/src/main/java/org/whispersystems/libsignal/protocol/SenderKeyDistributionMessage.java, java/java/src/main/java/org/whispersystems/libsignal/protocol/SenderKeyMessage.java, java/java/src/main/java/org/whispersystems/libsignal/protocol/SignalMessage.java, node/Native.d.ts, node/index.ts, node/test/PublicAPITest.ts, rust/bridge/shared/src/protocol.rs, rust/protocol/src/group_cipher.rs, rust/protocol/src/proto/storage.proto, rust/protocol/src/protocol.rs, rust/protocol/src/sender_keys.rs, swift/Sources/SignalClient/messages/PreKeySignalMessage.swift, swift/Sources/SignalClient/messages/SenderKeyDistributionMessage.swift, swift/Sources/SignalClient/messages/SenderKeyMessage.swift, swift/Sources/SignalClient/messages/SignalMessage.swift, swift/Sources/SignalFfi/signal_ffi.h
...or it should fail to decrypt. This parallels a similar check for SignalMessage and SessionState. Since we haven't been storing this field previously, treat a default "0" value as if it were version 3, the current version.
Additionally, when creating new messages we should use the session's version rather than the current version, also matching SignalMessage. We still encode the "current" version in the message version byte, but the part that the receiver checks is now based on the session's version rather than the "current" version in the sender. (Note that these are the *same* version right now, so this change won't have any effect on the current wire format.)
Finally, remove the direct-construction API for all \*Message types in Java, Swift, and TypeScript; these should always be …
=> A SenderKeyMessage's version must match the SenderKeyState

java/java/src/main/java/org/whispersystems/libsignal/groups/state/SenderKeyStore.java
The summary was out of sync with the `@return` command.
=> Java: fix doc comment for SenderKeyStore.loadSenderKey

java/java/src/main/java/org/signal/internal/Native.java, java/java/src/main/java/org/signal/libsignal/metadata/SealedSessionCipher.java, java/tests/src/test/java/org/signal/libsignal/metadata/SealedSessionCipherTest.java, node/Native.d.ts, node/index.ts, node/test/PublicAPITest.ts, rust/bridge/jni/bin/gen_java_decl.py, rust/bridge/node/bin/gen_ts_decl.py, rust/bridge/shared/src/ffi/convert.rs, rust/bridge/shared/src/jni/convert.rs, rust/bridge/shared/src/jni/mod.rs, rust/bridge/shared/src/node/convert.rs, rust/bridge/shared/src/protocol.rs, rust/protocol/src/sealed_sender.rs, rust/protocol/tests/groups.rs, rust/protocol/tests/sealed_sender.rs, swift/Sources/SignalClient/SealedSender.swift, swift/Sources/SignalFfi/signal_ffi.h, swift/Tests/SignalClientTests/SessionTests.swift
Registration IDs are used to detect if a device ID has been reused, since the new device will (with high probability) use a different randomly-generated registration ID from the old one. The server should be able to validate this for SSv2 like it does for SSv1, though the handling of this for SSv1 is in the various apps.
=> Add registration IDs to the Sealed Sender v2 upload (encrypt) format

rust/device-transfer/src/lib.rs, rust/protocol/src/address.rs, rust/protocol/src/lib.rs, swift/Sources/SignalFfi/signal_ffi.h
This is the first in a set of planned PRs to add inline documentation to the Rust API which can then be beautifully published with `cargo doc`. See #285.
**I am not a Signal engineer. I am making my best guesses as to the appropriate docstring content. I think I've been able to do just fine, but please push back if I'm mischaracterizing anything -- it's easy for me to just revert anything that seems possibly too bikesheddable.**
1. Add module docs for the `libsignal_protocol` crate.
1. Add docs to the `device_transfer` crate.
1. Add docs to the `address` module.
We will have established a rapport for further improvements to the documentation and module layout as per #285!
=> Add docstrings for a few small modules!

Cargo.lock, Cargo.toml, rust/bridge/node/Cargo.toml, rust/bridge/shared/Cargo.toml
See [signalapp/neon](/signalapp/neon) and neon-bindings/neon#739.
=> Node: Switch to our fork of Neon with faster EventQueue operations

rust/bridge/shared/src/jni/mod.rs
Not all Exception types have a constructor that takes a String; for those that don't, we can't use JNI's built-in `throw_new` API. Tested by deliberately panicking within our recovery logic.
=> JNI: correctly throw exceptions that don't have a String constructor

java/java/src/main/java/org/signal/internal/Native.java, java/java/src/main/java/org/signal/libsignal/metadata/SealedSessionCipher.java, java/java/src/main/java/org/whispersystems/libsignal/state/SessionRecord.java, java/java/src/main/java/org/whispersystems/libsignal/state/SessionStore.java, java/java/src/main/java/org/whispersystems/libsignal/state/impl/InMemorySessionStore.java, java/java/src/main/java/org/whispersystems/libsignal/state/impl/InMemorySignalProtocolStore.java, node/Native.d.ts, node/index.ts, node/test/PublicAPITest.ts, rust/bridge/node/bin/gen_ts_decl.py, rust/bridge/shared/src/node/convert.rs, rust/bridge/shared/src/protocol.rs, rust/protocol/src/sealed_sender.rs, rust/protocol/src/storage/inmem.rs, rust/protocol/tests/groups.rs, rust/protocol/tests/sealed_sender.rs, swift/Sources/SignalClient/DataStoreInMemory.swift, swift/Sources/SignalClient/DataStoreProtocols.swift, swift/Sources/SignalClient/SealedSender.swift, swift/Sources/SignalFfi/signal_ffi.h, swift/Tests/SignalClientTests/SessionTests.swift
The app-visible change is that `sealedSenderMultiRecipientEncrypt` now takes a SessionStore as well. Sessions will be looked up in bulk using a new SessionStore API, `loadExistingSessions` or `getExistingSessions` (just slightly different names across the different app languages). The registration ID is then loaded from each session and included in the resulting SSv2 payload.
The implementation is a bit of a divergence from some other APIs in libsignal-client in that the "look up in bulk" step is performed in the Java, Swift, or TypeScript layer, with the resulting sessions passed down to Rust. Why? Because otherwise we'd pass a list of addresses into Rust, which would have to turn them back into a Java, Swift, or TypeScript array to call the SessionStore method. This would be (1) a bunch …
=> Get registration IDs from sessions for Sealed Sender v2

java/java/src/main/java/org/signal/libsignal/metadata/protocol/UnidentifiedSenderMessageContent.java, java/tests/src/test/java/org/signal/libsignal/metadata/SealedSessionCipherTest.java, node/index.ts, node/test/PublicAPITest.ts, rust/bridge/shared/src/protocol.rs, rust/protocol/src/proto/sealed_sender.proto, rust/protocol/src/sealed_sender.rs, rust/protocol/tests/groups.rs, swift/Sources/SignalClient/SealedSender.swift, swift/Sources/SignalFfi/signal_ffi.h, swift/Tests/SignalClientTests/SessionTests.swift
- Default: sender will not resend; an error should be shown immediately
- Resendable: sender will try to resend; delay any error UI if possible
- Implicit: don't show any error UI at all; this is something sent implicitly like a typing message or a receipt
=> Finalize ContentHint design

java/java/src/main/java/org/signal/internal/Native.java, java/java/src/main/java/org/signal/libsignal/metadata/SealedSessionCipher.java, java/java/src/main/java/org/whispersystems/libsignal/protocol/CiphertextMessage.java, java/java/src/main/java/org/whispersystems/libsignal/protocol/DecryptionErrorMessage.java, java/java/src/main/java/org/whispersystems/libsignal/protocol/PlaintextContent.java, java/java/src/main/java/org/whispersystems/libsignal/state/SessionRecord.java, java/tests/src/test/java/org/signal/libsignal/metadata/SealedSessionCipherTest.java, java/tests/src/test/java/org/whispersystems/libsignal/SessionCipherTest.java, node/Native.d.ts, node/index.ts, node/test/PublicAPITest.ts, rust/bridge/shared/src/jni/convert.rs, rust/bridge/shared/src/jni/mod.rs, rust/bridge/shared/src/protocol.rs, rust/protocol/build.rs, rust/protocol/src/lib.rs, rust/protocol/src/proto.rs, rust/protocol/src/proto/sealed_sender.proto, rust/protocol/src/proto/service.proto, rust/protocol/src/proto/service.rs, rust/protocol/src/protocol.rs, rust/protocol/src/sealed_sender.rs, rust/protocol/src/state/session.rs, rust/protocol/tests/sealed_sender.rs, swift/Sources/SignalClient/messages/CiphertextMessage.swift, swift/Sources/SignalClient/messages/PlaintextContent.swift, swift/Sources/SignalClient/state/SessionRecord.swift, swift/Sources/SignalFfi/signal_ffi.h, swift/Tests/SignalClientTests/SessionTests.swift
An alternative to #315 that avoids having a separate PlaintextContent *proto* while still having a PlaintextContent *type* (to prevent encoding messages that should be encrypted as plaintext). This makes the decryption side uniform with existing message types.
* * *
These will be used to help reset 1:1 and SenderKey sessions when messages fail to decrypt, rather than ending up in a state where message after message fails to decrypt. (1:1 sessions already have a form of automatic session reset in recent releases of Signal, but this provides a bit more feedback.)
=> Add DecryptionErrorMessage and PlaintextContent (alternate)

java/java/src/main/java/org/signal/libsignal/metadata/ProtocolDuplicateMessageException.java, java/java/src/main/java/org/signal/libsignal/metadata/ProtocolException.java, java/java/src/main/java/org/signal/libsignal/metadata/ProtocolInvalidKeyException.java, java/java/src/main/java/org/signal/libsignal/metadata/ProtocolInvalidKeyIdException.java, java/java/src/main/java/org/signal/libsignal/metadata/ProtocolInvalidMessageException.java, java/java/src/main/java/org/signal/libsignal/metadata/ProtocolInvalidVersionException.java, java/java/src/main/java/org/signal/libsignal/metadata/ProtocolLegacyMessageException.java, java/java/src/main/java/org/signal/libsignal/metadata/ProtocolNoSessionException.java, java/java/src/main/java/org/signal/libsignal/metadata/ProtocolUntrustedIdentityException.java, java/java/src/main/java/org/signal/libsignal/metadata/SealedSessionCipher.java
That is, when there's an error decrypting the inner payload of a sealed sender message, instead of just saving the sender (and more recently the content hint and group ID), save the whole decrypted contents of the sealed sender message. This is necessary so that the app can make a DecryptedErrorMessage from that failed payload.
This is complicated somewhat by the fact that the app also uses the "short" constructor for the various Protocol*Exceptions, so we have to keep those working.
=> Java: put the UnidentifiedSenderMessageContent in a ProtocolException

java/java/src/main/java/org/signal/internal/Native.java, java/java/src/main/java/org/whispersystems/libsignal/protocol/DecryptionErrorMessage.java, java/tests/src/test/java/org/signal/libsignal/metadata/SealedSessionCipherTest.java, node/Native.d.ts, node/index.ts, node/test/PublicAPITest.ts, rust/bridge/shared/src/protocol.rs, rust/protocol/src/proto/service.proto, rust/protocol/src/protocol.rs, rust/protocol/tests/sealed_sender.rs, swift/Sources/SignalClient/messages/PlaintextContent.swift, swift/Sources/SignalFfi/signal_ffi.h, swift/Tests/SignalClientTests/SessionTests.swift
This allows a device to know whether it's the one that sent a bad message, and take action accordingly.
We could have a slightly more typesafe API here by using ProtocolAddress and extracting the device ID, but that doesn't match up with getting the device ID out of a sealed sender certificate (which provides separate "sender UUID", "sender phone number", and "sender device ID" fields).
=> Add a deviceId field to DecryptionErrorMessage

java/java/src/main/java/org/signal/libsignal/metadata/SealedSessionCipher.java, java/tests/src/test/java/org/signal/libsignal/metadata/SealedSessionCipherTest.java
This is useful for PlaintextContent messages (just DecryptionErrorMessage for now), which can't include a group ID when sent outside of sealed sender because it would reveal group membership.
=> Java: include the sealed sender groupId on sucessful decryption

rust/crypto/src/aes_ctr.rs
Very large initial counter values would overflow the computation of the initial offset. Use u64 even on 32-bit platforms to avoid this.
This was introduced in #328, so it's not a problem in any shipping versions of libsignal-client.
=> crypto: Fix a 32-bit overflow in AES-256-CTR

Cargo.lock, rust/bridge/ffi/Cargo.toml, rust/bridge/ffi/src/lib.rs, rust/bridge/node/futures/Cargo.toml, rust/bridge/node/futures/src/promise.rs, rust/bridge/node/futures/tests-node-module/Cargo.toml, rust/bridge/node/futures/tests-node-module/src/store_like.rs, rust/bridge/shared/Cargo.toml, rust/bridge/shared/macros/src/ffi.rs, rust/bridge/shared/macros/src/jni.rs, rust/bridge/shared/src/ffi/mod.rs, rust/bridge/shared/src/jni/mod.rs, rust/bridge/shared/src/protocol.rs, rust/bridge/shared/src/support/mod.rs, rust/protocol/Cargo.toml, rust/protocol/benches/ratchet.rs, rust/protocol/benches/session.rs, rust/protocol/tests/groups.rs, rust/protocol/tests/sealed_sender.rs, rust/protocol/tests/session.rs
Both `futures::executor::block_on` and our own `expect_ready` were being used to resolve futures that were, in practice, known to be non-blocking. `FutureExt::now_or_never` handles that case more lightly than `block_on` and more uniformly than `expect_ready`.
This lets us drop the dependency on the full 'futures' crate down to just futures-util, which should help with compile time.
=> Replace block_on and expect_ready with FutureExt::now_or_never

Cargo.lock, rust/protocol/Cargo.toml, rust/protocol/src/fingerprint.rs, rust/protocol/src/identity_key.rs, rust/protocol/src/sealed_sender.rs, rust/protocol/src/sender_keys.rs, rust/protocol/src/state/prekey.rs, rust/protocol/src/state/session.rs, rust/protocol/src/state/signed_prekey.rs
The dreaded https://github.com/tokio-rs/prost/issues/154 (Prost Message `vec![]` + `encode` + `expect`) can now be get rid of in most places, thanks to https://github.com/tokio-rs/prost/pull/378. In some places, I've left the `.encode` call because it's doing some prepending of magic bytes.
=> Upgrade prost to 0.8

Cargo.lock, Cargo.toml, rust/bridge/node/Cargo.toml, rust/bridge/node/futures/Cargo.toml, rust/bridge/node/futures/src/exception.rs, rust/bridge/node/futures/src/executor.rs, rust/bridge/node/futures/src/future.rs, rust/bridge/node/futures/src/future/builder.rs, rust/bridge/node/futures/src/lib.rs, rust/bridge/node/futures/src/promise.rs, rust/bridge/node/futures/tests-node-module/Cargo.toml, rust/bridge/node/futures/tests-node-module/src/lib.rs, rust/bridge/node/futures/tests-node-module/src/store_like.rs, rust/bridge/node/src/logging.rs, rust/bridge/shared/Cargo.toml, rust/bridge/shared/src/node/storage.rs
- Drop our fork of Neon now that our changes have been integrated
- Adopt rename of EventQueue to Channel
- Add a `napi-6` feature to signal-neon-futures to make it easier to test under the configuration we're actually shipping
=> Update to Neon 0.9.0

.github/workflows/build_and_test.yml, rust/bridge/ffi/Cargo.toml, rust/bridge/jni/Cargo.toml, rust/bridge/node/Cargo.toml, rust/bridge/shared/Cargo.toml, rust/crypto/Cargo.toml, rust/protocol/Cargo.toml
Follow-up from #284, as promised. As you said, it became a lot easier :-)
Would you like me to make the armv8 feature default in the jni/node/native ffi crates? Maybe it makes sense there. Otherwise, you'll have to supply the armv8 feature flag from the build system in Signal-Android and Signal-iOS
(off topic: re NEON and Dalek, we have something upcoming!)
=> Put aes' armv8 feature behind nightly feature

.github/workflows/build_and_test.yml, rust/protocol/fuzz/.gitignore, rust/protocol/fuzz/Cargo.toml, rust/protocol/fuzz/README.md, rust/protocol/fuzz/fuzz_targets/interaction.rs, rust/protocol/src/protocol.rs, rust/protocol/src/session_cipher.rs
Based on the fuzzing input (provided by [cargo-fuzz](https://rust-fuzz.github.io/book/cargo-fuzz.html)), this simulates message sends and receives, out-of-order delivery, dropped messages, and session resets, solely to find bugs in happy-path interaction between two clients.
While here, improve the logging of 1:1 decryption:
- Downgrade per-session decryption errors to warnings, because we try multiple sessions for each decryption and emit a roll-up error at the end.
- Remove some accidental double hex-encoding (as in, we were hex-encoding the ASCII hex representation of a slice).
=> protocol: Add a fuzz target that runs interactions between two clients

rust/protocol/src/sealed_sender.rs, rust/protocol/tests/sealed_sender.rs
...in the error. This should help apps debug when a session is archived but they still think a recipient is prepared to receive sender-key messages. (If they were sending 1:1 messages, they would have caught this earlier.)
=> SSv2: when fetching a registration ID fails, mention the recipient

rust/protocol/Cargo.toml, rust/protocol/benches/sealed_sender.rs, rust/protocol/src/curve.rs, rust/protocol/src/curve/curve25519.rs, rust/protocol/src/sealed_sender.rs
Identity keys are tied to an account, not a device, so when a multi-recipient sealed sender message is sent to every device for a particular account, a lot of work is wasted re-encoding the ephemeral message key and authentication tag for each device. This commit checks to see if the current identity key is the same as the previous one and reuses the previous encrypted message key and authentication tag if so, drastically reducing the marginal cost of another linked device (from ~200ms to ~2ms on my machine).
=> Sealed Sender v2: reuse work when sending to the same identity key

rust/crypto/Cargo.toml
This was a rebase failure where the armv8 support in signal-crypto dependencies was not actually put behind the armv8 flag. Our CI didn't catch it because we don't do a build that's both stable *and* targeting aarch64, but for completeness we should get it right.
=> Fix armv8 feature flag for signal-crypto

rust/protocol/src/sealed_sender.rs, rust/protocol/src/session.rs, rust/protocol/src/session_cipher.rs
- Log on every successful decryption, including the session base key. (Previously this was just a debug-level log.)
- Log the sender for sucessful decryptions.
- Log when we process a pre-key message.
- To balance this out, don't log "we're about to deserialize a sealed sender message" (downgrade it to debug).
=> protocol: More logging for successful decryption of 1:1 messages

java/build_jni.sh, java/check_code_size.py
This is a step towards saving the debug info somewhere for the builds we actually ship on Android, but for now it's enough to have the unstripped libraries *available* for testing purposes.
=> Java: don't eagerly strip libsignal_client.so; let gradle do it for us

java/java/src/main/java/org/signal/libsignal/metadata/ProtocolException.java, java/java/src/main/java/org/signal/libsignal/metadata/SealedSessionCipher.java, java/java/src/main/java/org/whispersystems/libsignal/InvalidRegistrationIdException.java, java/tests/src/test/java/org/signal/libsignal/metadata/SealedSessionCipherTest.java, node/Address.ts, node/Errors.ts, node/index.ts, node/test/PublicAPITest.ts, rust/bridge/ffi/src/lib.rs, rust/bridge/ffi/src/util.rs, rust/bridge/shared/src/jni/mod.rs, rust/bridge/shared/src/jni/storage.rs, rust/bridge/shared/src/node/error.rs, rust/protocol/src/error.rs, rust/protocol/src/sealed_sender.rs, rust/protocol/tests/sealed_sender.rs, swift/Sources/SignalClient/DataStoreInMemory.swift, swift/Sources/SignalClient/Error.swift, swift/Sources/SignalClient/Utils.swift, swift/Sources/SignalFfi/signal_ffi.h, swift/Tests/.swiftlint.yml, swift/Tests/SignalClientTests/SessionTests.swift
This dedicated error is thrown when a recipient has a registration ID that's out of the range used by Signal [0, 0x3FFF]. These IDs cannot be encoded in the sealed sender v2 format and are not supported, even though they don't cause any problems for 1:1 messages.
=> Sealed sender v2: add an InvalidRegistrationId exception/error

Cargo.lock, rust/poksho/Cargo.toml, rust/protocol/Cargo.toml
Signal has [a fork of curve25519-dalek](https://github.com/signalapp/curve25519-dalek) to add some features that are used by [zkgroup](https://github.com/signalapp/zkgroup). However, libsignal-protocol and poksho don't use those features directly, and thus they don't depend on our fork specifically. Anyone outside of Signal using libsignal-protocol can thus use the standard curve25519-dalek and avoid building it twice. Signal will continue using our fork thanks to the [workspace patch in the root Cargo.toml](https://github.com/signalapp/libsignal-client/blob/a7bf2261660f98065d0c34a81114ad41651ba553/Cargo.toml#L20-L21).
Additionally, remove all the passthrough features for customizing curve25519-dalek; we don't use any of them, and clients can always specify them directly.
=> Simplify curve25519-dalek dependency

rust/protocol/src/curve.rs, rust/protocol/src/curve/curve25519.rs, rust/protocol/src/identity_key.rs, rust/protocol/src/sealed_sender.rs
- Cache the computation for ephemeral keys in sealed sender v2
- Pass through the public key when we have a key pair already
- Stop deriving it and then ignoring it for low-level curve25519 operations
=> Stop deriving curve25519 public keys when we don't need to

README.md, java/Makefile, java/build.gradle, swift/README.md, swift/build_ffi.sh
- Add an error message for missing rust-src when using xargo (addresses #361)
- Update build instructions for Java and for Swift (addresses #363, among other improvements)
- Run `cargo clean` as part of `gradlew clean`, but don't clean every time when using the Docker build (addresses https://community.signalusers.org/t/build-libsignal-client-to-produce-signal-client-android-aar/36045/5)
=> Tweak the build to be more friendly

rust/protocol/src/kdf.rs, rust/protocol/src/sealed_sender.rs
Hello! I am going to finish up my other pending PRs to this repo soon :).
The sealed sender single-recipient and multi-recipient KEM schemes in Sealed Sender v1/v2 are super neat, and documentation for how they work exists in some (very helpful!) source comments. However, it's not immediately clear e.g. that the Signal server receives the result of `sealed_sender_multi_recipient_encrypt()`, splits the output into constituent sealed-sender v2 messages, then routes them individually to clients for `sealed_sender_multi_recipient_decrypt()`. Additionally, the design tradeoffs between v1 and v2 sealed sender mechanisms in general are not made clear in documentation of these public methods.
1. Move the (very useful!) documentation for the mechanism of v1 and v2 sealed sender into the docstrings …
=> Move docs for sealed sender v1/v2 to the appropriate method docstrings

node/Native.d.ts, rust/bridge/node/bin/Native.d.ts.in, rust/bridge/shared/src/ffi/convert.rs, rust/bridge/shared/src/jni/convert.rs, rust/bridge/shared/src/node/convert.rs, rust/bridge/shared/src/protocol.rs
u64 can't be represented as a primitive in Java or TypeScript (and for the latter, [Neon doesn't support bigint yet](https://github.com/neon-bindings/neon/issues/376)). However, for timestamps represented as milliseconds, the integer-safe range of float64 still covers more than 285,000 years, so it's reasonably safe to use TypeScript's 'number' or Java's 'long' to represent these ostensibly-64-bit values. Indicate this with a new Timestamp wrapper type in the bridge layer.
In theory we could push this new Timestamp type down to the libsignal-protocol crate. However, the protocol itself doesn't impose any restrictions on the timestamp fields, so I figured it was best to put it at the bridge layer, to indicate that it's about how Signal specifically uses these fields.
This commit paves the …
=> bridge: Be more explicit about bridging u64 timestamps

rust/bridge/node/bin/gen_ts_decl.py, rust/bridge/shared/src/jni/convert.rs, rust/bridge/shared/src/node/convert.rs
- FFI: still maps trivially to uint64_t, no change
- JNI: reinterpret as jlong (i64) to not lose any information
- Node: until Neon supports bigints, convert to/from a big-endian Buffer
Follow-up to #404.
=> bridge: Add back support for bridging u64, now losslessly

Cargo.lock, java/java/src/main/java/org/signal/client/internal/Native.java, node/Native.d.ts, rust/bridge/ffi/Cargo.toml, rust/bridge/ffi/cbindgen.toml, rust/bridge/ffi/src/util.rs, rust/bridge/shared/Cargo.toml, rust/bridge/shared/src/ffi/convert.rs, rust/bridge/shared/src/ffi/error.rs, rust/bridge/shared/src/jni/convert.rs, rust/bridge/shared/src/jni/error.rs, rust/bridge/shared/src/jni/mod.rs, rust/bridge/shared/src/lib.rs, rust/bridge/shared/src/node/error.rs, rust/bridge/shared/src/support/serialized.rs, rust/bridge/shared/src/zkgroup.rs, swift/Sources/SignalFfi/signal_ffi.h
These APIs are designed to match the generated "simpleapi" entry points in [the original zkgroup repository](/signalapp/zkgroup), to make it easier to adapt the existing Java, Swift, and TypeScript code to libsignal-client.
The cbindgen-generated signal_ffi.h now includes constants, so that the fixed-size arrays used to serialize zkgroup types can use named constants in Rust. This meant filtering out some constants that were getting picked up but that should not be included.
Note that this commit makes references to Java exception types that will be added in a later commit.
=> bridge: Add zkgroup APIs

.github/workflows/jni_artifacts.yml, .gitignore, RELEASE.md, java/build_jni.sh, java/java/build.gradle
This is like signal-client-java, but also contains dylibs for Mac and Windows for testing purposes. This is something [zkgroup](/signalapp/zkgroup) already has; in particular it allows developers working on the [server](/signalapp/Signal-Server) to use the zkgroup APIs even if they run macOS or Windows on their individual machines. The first commit builds the libraries as a GitHub Action whenever a new release is tagged; the second adds a new Gradle target that automatically downloads those libraries and includes them in the new jar output.
=> java: Build a "testable" signal-client-java as well

java/android/build.gradle
This allows us to symbolicate native crash traces if necessary.
=> Android: upload unstripped libraries to Maven as well

swift/Sources/SignalClient/zkgroup/AuthCredential.swift, swift/Sources/SignalClient/zkgroup/AuthCredentialPresentation.swift, swift/Sources/SignalClient/zkgroup/AuthCredentialResponse.swift, swift/Sources/SignalClient/zkgroup/ByteArray.swift, swift/Sources/SignalClient/zkgroup/GroupPublicParams.swift, swift/Sources/SignalClient/zkgroup/GroupSecretParams.swift, swift/Sources/SignalClient/zkgroup/ProfileKeyCiphertext.swift, swift/Sources/SignalClient/zkgroup/ProfileKeyCommitment.swift, swift/Sources/SignalClient/zkgroup/ProfileKeyCredential.swift, swift/Sources/SignalClient/zkgroup/ProfileKeyCredentialPresentation.swift, swift/Sources/SignalClient/zkgroup/ProfileKeyCredentialRequest.swift, swift/Sources/SignalClient/zkgroup/ProfileKeyCredentialRequestContext.swift, swift/Sources/SignalClient/zkgroup/ProfileKeyCredentialResponse.swift, swift/Sources/SignalClient/zkgroup/ReceiptCredential.swift, swift/Sources/SignalClient/zkgroup/ReceiptCredentialPresentation.swift, swift/Sources/SignalClient/zkgroup/ReceiptCredentialRequest.swift, swift/Sources/SignalClient/zkgroup/ReceiptCredentialRequestContext.swift, swift/Sources/SignalClient/zkgroup/ReceiptCredentialResponse.swift, swift/Sources/SignalClient/zkgroup/ServerPublicParams.swift, swift/Sources/SignalClient/zkgroup/ServerSecretParams.swift, swift/Sources/SignalClient/zkgroup/UuidCiphertext.swift, swift/Tests/SignalClientTests/ZKGroupTests.swift
Don't validate sizes explicitly; they're already provided in the signatures of the *_check_valid_contents functions exposed in the FFI layer. Similar to #408.
=> swift: Improve zkgroup's ByteArray helper class

node/test/ZKGroup-test.ts, node/zkgroup/NotarySignature.ts, node/zkgroup/ServerPublicParams.ts, node/zkgroup/ServerSecretParams.ts, node/zkgroup/auth/AuthCredential.ts, node/zkgroup/auth/AuthCredentialPresentation.ts, node/zkgroup/auth/AuthCredentialResponse.ts, node/zkgroup/groups/GroupIdentifier.ts, node/zkgroup/groups/GroupMasterKey.ts, node/zkgroup/groups/GroupPublicParams.ts, node/zkgroup/groups/GroupSecretParams.ts, node/zkgroup/groups/ProfileKeyCiphertext.ts, node/zkgroup/groups/UuidCiphertext.ts, node/zkgroup/internal/ByteArray.ts, node/zkgroup/profiles/ProfileKey.ts, node/zkgroup/profiles/ProfileKeyCommitment.ts, node/zkgroup/profiles/ProfileKeyCredential.ts, node/zkgroup/profiles/ProfileKeyCredentialPresentation.ts, node/zkgroup/profiles/ProfileKeyCredentialRequest.ts, node/zkgroup/profiles/ProfileKeyCredentialRequestContext.ts, node/zkgroup/profiles/ProfileKeyCredentialResponse.ts, node/zkgroup/profiles/ProfileKeyVersion.ts, node/zkgroup/receipts/ReceiptCredential.ts, node/zkgroup/receipts/ReceiptCredentialPresentation.ts, node/zkgroup/receipts/ReceiptCredentialRequest.ts, node/zkgroup/receipts/ReceiptCredentialRequestContext.ts, node/zkgroup/receipts/ReceiptCredentialResponse.ts, node/zkgroup/receipts/ReceiptSerial.ts
Don't validate sizes explicitly; that's already handled by the *_CheckValidContents functions exposed in the bridge layer. Same idea as #408 and #412.
=> node: Improve zkgroup's ByteArray helper class

java/java/src/main/java/org/signal/client/internal/Native.java, java/java/src/main/java/org/signal/zkgroup/groups/ClientZkGroupCipher.java, node/Native.d.ts, node/zkgroup/groups/ClientZkGroupCipher.ts, rust/bridge/jni/bin/gen_java_decl.py, rust/bridge/shared/src/zkgroup.rs, rust/zkgroup/src/api/groups/group_params.rs, swift/Sources/SignalClient/zkgroup/ClientZkGroupCipher.swift, swift/Sources/SignalFfi/signal_ffi.h
Previously this was defined in the app layers, because zkgroup's original codegen didn't support custom exception types. However, we can now move it to a common implementation in Rust.
~~This could live in libsignal-bridge, or in the zkgroup crate proper. I chose libsignal-bridge because padding isn't an inherent requirement for the zkgroup encryption format, but it could go either way.~~
=> zkgroup: Move blob padding/unpadding into Rust

rust/zkgroup/src/api/groups/group_params.rs
There's no point in taking GroupSecretParams by value here; it's a Copy type already. I suspect it was a typo originally.
=> zkgroup: GroupSecretParams::decrypt_blob should use `&self`

Cargo.lock, rust/protocol/Cargo.toml
Prost 0.9 contains some performance improvement for varint, and allows developers to work on Apple silicon.
https://github.com/tokio-rs/prost/releases/tag/v0.9.0
Technically this is a breaking change (because `prost::DecodeError` is exposed through `SignalProtocolError`), so you'll want to bump to 0.12 after this.
=> Update to prost 0.9

rust/bridge/jni/src/logging.rs, rust/bridge/shared/src/jni/args.rs, rust/bridge/shared/src/jni/convert.rs, rust/bridge/shared/src/jni/error.rs, rust/bridge/shared/src/jni/mod.rs, rust/bridge/shared/src/jni/storage.rs
- `jni_class_name` turns Java-style dotted class names into JNI-style slash-separated names.
- `jni_args` builds on `jni_signature` to make sure the arguments passed to a function match the declared signature. It also records the expected return type so `call_method_checked` can convert to it automatically.
=> bridge: add jni_class_name and jni_args helper macros

.github/workflows/npm.yml
This requires building on the macOS 11 GitHub runner; the 10.15 runner isn't set up for cross-compiling when not using Xcode.
Also, ensure that when we test the NPM package before publishing, we're using the libraries we're going to submit, rather than ones built on the final runner.
=> NPM: Publish releases for M1 Macs too

.github/workflows/build_and_test.yml
...because the fuzz target doesn't have a lockfile, and crates don't generally support arbitrary nightly versions. (Specifically, we just hit dtolnay/proc-macro2#307.)
=> GitHub: Move fuzz target checking to the stable Rust toolchain job

rust/bridge/ffi/src/util.rs, rust/bridge/shared/src/jni/mod.rs, rust/protocol/src/crypto.rs, rust/protocol/src/error.rs, rust/protocol/src/group_cipher.rs, rust/protocol/src/ratchet.rs, rust/protocol/src/ratchet/keys.rs, rust/protocol/src/sealed_sender.rs, rust/protocol/src/sender_keys.rs, rust/protocol/src/session_cipher.rs, rust/protocol/src/state/session.rs
Use fixed-length arrays and dedicated error types to force the callers of crate-internal crypto operations to deal with errors, usually by treating a session as corrupted (i.e. something that should not happen using only the libsignal-client APIs to manipulate sessions). This keeps from propagating context-less errors out to callers, and removes the need for error propagation altogether in some cases. It also ends up removing three specific flavors of SignalProtocolError that were already being treated as unexpected runtime exceptions.
=> protocol: Tighten up error handling for internal crypto operations

rust/bridge/shared/src/ffi/storage.rs, rust/bridge/shared/src/jni/storage.rs, rust/protocol/src/session_cipher.rs, rust/protocol/src/state/session.rs
And straighten out InvalidState (a precondition the caller failed to enforce) vs. InternalError (something went wrong that the caller couldn't have checked for).
=> protocol: Tidy up some error strings

java/java/src/main/java/org/signal/client/internal/Native.java, java/java/src/main/java/org/whispersystems/libsignal/IdentityKey.java, java/java/src/main/java/org/whispersystems/libsignal/IdentityKeyPair.java, java/tests/src/test/java/org/whispersystems/libsignal/IdentityKeyTest.java, node/Native.d.ts, node/ts/index.ts, node/ts/test/PublicAPITest.ts, rust/bridge/shared/src/protocol.rs, rust/protocol/src/curve.rs, rust/protocol/src/curve/curve25519.rs, rust/protocol/src/identity_key.rs, swift/Sources/SignalClient/IdentityKey.swift, swift/Sources/SignalFfi/signal_ffi.h, swift/Tests/SignalClientTests/PublicAPITests.swift
This can be used for one identity to attest that another identity represents the same account. For instance, a PNI can sign an ACI to demonstrate that the ACI is associated with the phone number in question.
=> Add signAlternateIdentity and verifyAlternateIdentity operations

.github/workflows/npm.yml
This PR adds prebuilds for Windows ARM64 to CI. I've been [building these in my fork](https://github.com/dennisameling/libsignal-node/tree/main/prebuilds/win32-arm64) for a few months and haven't encountered issues with it.
As discussed in https://github.com/signalapp/libsignal-client/pull/426#issuecomment-998233937, "discussion with the Desktop folks is leaning positive about it", so I took the liberty to create this PR 😊
=> node: Add Windows ARM64 prebuilds to CI

java/java/src/main/java/org/whispersystems/libsignal/protocol/PlaintextContent.java, java/tests/src/test/java/org/whispersystems/libsignal/PlaintextContentTest.java
This is necessary when handling PlaintextContent *not* sent via sealed sender.
=> java: Add PlaintextContent(byte[]) constructor

rust/protocol/src/fingerprint.rs
I noticed there was a todo left in the comments :)
Should `read5_mod_100k` perhaps use `u64::from_be_bytes`? It would be more readable/understandable.
=> Update to string encoding for fingerprint

java/java/src/main/java/org/signal/libsignal/metadata/SealedSessionCipher.java
We'd like to be able to know what kind of message the SealedSessionCipher processed.
=> Added message type to sealed sender decryption result.

swift/Sources/SignalClient/HsmEnclave.swift, swift/Tests/SignalClientTests/HsmEnclaveTests.swift
commit a7a874d8195f803609a2c3a5925699ee71d20d12
Author: Michelle Linington <michelle@signal.org>
Date:   Fri Feb 11 14:14:15 2022 -0800
Fix broken tests
commit e2fe069d38c303f6a049613ddef99fd087677578
Author: Michelle Linington <michelle@signal.org>
Date:   Thu Feb 10 15:25:08 2022 -0800
Tweaks the Swift interface for HSM Enclave Client
- Fixes an issue where a call to decrypt would instead re-encrypt the
ciphertext.
- Tweaks the interface for the initializer to instead take raw public
key bytes. This matches the java interface. Framework clients have no
way to construct a PublicKey from raw bytes.
=> Tweaks the Swift interface for HSM Enclave Client

.github/workflows/npm.yml
As mentioned in https://github.com/signalapp/libsignal-client/pull/426#issuecomment-1035334639
Linux is a bit of a special case in that we need to explicitly define things like the arm64 linker. Without the cross dependencies, I got linker errors: https://github.com/dennisameling/libsignal-client/runs/5229605777?check_suite_focus=true
Example of a successful build: https://github.com/dennisameling/libsignal-client/actions/runs/1858014293
I've been using this setup in my `signal-native-deps` repo for a few months: https://github.com/dennisameling/signal-native-deps/blob/75f22a11a11d18b1ed3b85b51d032816579cce00/.github/workflows/build.yaml#L132-L140
=> NPM: publish releases for Linux arm64

node/ts/index.ts, node/ts/test/HsmEnclaveTest.ts
The PublicKey type includes a type byte prefix to support different kinds of public keys in the future, but that doesn't really apply to HsmEnclave keys. This matches the Java implementation and the recently-updated Swift implementation (#448)
=> Node: use a plain Buffer for the HsmEnclave public key
